## Import Libraries

In [13]:
import pandas as pd

## Load the Dataset

In [14]:
df = pd.read_csv("../data/student_version.csv")

C:\Users\sarag\AppData\Local\Temp\ipykernel_5724\2254339070.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/student_version.csv")

# Explore the Dataset

Before performing data cleaning and feature engineering, it is important to explore the dataset to understand its overall structure and quality.

The exploration process includes:

- Checking the dataset dimensions.
- Examining the data types of each column.
- Computing descriptive statistics.
- Identifying missing values.
- Inspecting duplicate records.
- Reviewing unique values in categorical variables.

Understanding these characteristics helps determine the appropriate preprocessing techniques before building the prediction model.

In [15]:
print("=" * 70)
print("DATASET SHAPE")
print(df.shape)

print("\n" + "=" * 70)
print("DATASET INFORMATION")
df.info()

print("\n" + "=" * 70)
print("DESCRIPTIVE STATISTICS")
display(df.describe(include="all"))

print("\n" + "=" * 70)
print("MISSING VALUES")
display(df.isnull().sum().sort_values(ascending=False))

print("\n" + "=" * 70)
print("FIRST FIVE ROWS")
display(df.head())

print("\n" + "=" * 70)
print("LAST FIVE ROWS")
display(df.tail())

print("=" * 70)
print("DUPLICATED ROWS")
print(df.duplicated().sum())

print("\n" + "=" * 70)
print("DATA TYPES")
display(df.dtypes)

print("\n" + "=" * 70)
print("UNIQUE VALUES PER COLUMN")
display(df.nunique())

======================================================================
DATASET SHAPE
(110938, 190)

======================================================================
DATASET INFORMATION
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110938 entries, 0 to 110937
Columns: 190 entries, match_id to away_club_recent_competition_code_10
dtypes: float64(162), int64(2), object(26)
memory usage: 160.8+ MB

======================================================================
DESCRIPTIVE STATISTICS

,match_id,match_result,home_club,away_club,fixture_date,competition,competition_code,cup_game,home_manager_id,away_manager_id,...,away_club_recent_competition_code_1,away_club_recent_competition_code_2,away_club_recent_competition_code_3,away_club_recent_competition_code_4,away_club_recent_competition_code_5,away_club_recent_competition_code_6,away_club_recent_competition_code_7,away_club_recent_competition_code_8,away_club_recent_competition_code_9,away_club_recent_competition_code_10
count,1.109380e+05,110938,110937,110937,110938,110937,110938.000000,110937,8.921700e+04,8.912300e+04,...,109712.000000,108345.000000,106904.000000,105422.000000,103938.000000,102512.000000,101071.000000,99643.000000,98176.000000,96722.000000
unique,NaN,3,9813,9892,20269,727,NaN,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,home,Al Ittihad,Al Ittihad,2020-09-19 14:00:00,Premier League,NaN,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,48113,91,82,201,5565,NaN,101856,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,1.519875e+07,NaN,NaN,NaN,NaN,NaN,910.457012,NaN,1.287134e+07,1.291552e+07,...,901.986200,894.389137,886.368012,878.243611,869.450297,861.901455,853.435338,844.673223,837.678200,829.177374
std,2.536393e+06,NaN,NaN,NaN,NaN,NaN,549.120985,NaN,1.578479e+07,1.580344e+07,...,545.826707,542.247411,538.497274,534.864981,531.170701,527.338931,524.217968,520.954647,517.647869,514.900676
min,1.142829e+07,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,2.000000e+00,2.000000e+00,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
25%,1.200038e+07,NaN,NaN,NaN,NaN,NaN,444.000000,NaN,4.596120e+05,4.595650e+05,...,438.000000,432.000000,426.000000,420.000000,417.000000,408.000000,399.000000,391.500000,387.000000,387.000000
50%,1.675988e+07,NaN,NaN,NaN,NaN,NaN,947.000000,NaN,1.552728e+06,1.552806e+06,...,944.000000,935.000000,906.500000,899.000000,884.000000,881.000000,860.000000,830.000000,821.000000,806.000000
75%,1.724230e+07,NaN,NaN,NaN,NaN,NaN,1293.000000,NaN,3.243116e+07,3.279539e+07,...,1286.000000,1283.000000,1279.000000,1274.000000,1270.000000,1267.000000,1265.000000,1263.000000,1261.000000,1255.000000
max,1.805384e+07,NaN,NaN,NaN,NaN,NaN,2039.000000,NaN,3.756849e+07,3.756847e+07,...,2039.000000,2039.000000,2039.000000,2039.000000,2039.000000,2039.000000,2039.000000,2039.000000,2028.000000,2025.000000

======================================================================
MISSING VALUES

away_club_recent_manager_id_10    27129
home_club_recent_manager_id_10    26653
away_club_recent_manager_id_9     26150
home_club_recent_manager_id_9     25733
away_club_recent_manager_id_8     25219
                                  ...
home_club                             1
competition_code                      0
match_id                              0
match_result                          0
fixture_date                          0
Length: 190, dtype: int64

======================================================================
FIRST FIVE ROWS

,match_id,match_result,home_club,away_club,fixture_date,competition,competition_code,cup_game,home_manager_id,away_manager_id,...,away_club_recent_competition_code_1,away_club_recent_competition_code_2,away_club_recent_competition_code_3,away_club_recent_competition_code_4,away_club_recent_competition_code_5,away_club_recent_competition_code_6,away_club_recent_competition_code_7,away_club_recent_competition_code_8,away_club_recent_competition_code_9,away_club_recent_competition_code_10
0,11906497,away,Newell's Old Boys,River Plate,2019-12-01 00:45:00,Superliga,636,False,468196.0,468200.0,...,1122.0,642.0,636.0,636.0,636.0,1122.0,636.0,642.0,636.0,1122.0
1,11984383,home,Real Estelí,Deportivo Las Sabanas,2019-12-01 01:00:00,Primera Division,752,False,516788.0,22169161.0,...,752.0,752.0,752.0,752.0,752.0,752.0,752.0,752.0,752.0,752.0
2,11983301,draw,UPNFM,Marathón,2019-12-01 01:00:00,Liga Nacional,734,False,2510608.0,456313.0,...,734.0,734.0,734.0,734.0,734.0,734.0,734.0,734.0,734.0,734.0
3,11983471,away,León,Morelia,2019-12-01 01:00:00,Liga MX,743,False,1552508.0,465797.0,...,743.0,743.0,743.0,743.0,743.0,743.0,743.0,743.0,746.0,743.0
4,11883005,home,Cobán Imperial,Iztapa,2019-12-01 01:00:00,Liga Nacional,705,False,429958.0,426870.0,...,705.0,705.0,705.0,705.0,705.0,705.0,705.0,705.0,705.0,705.0

======================================================================
LAST FIVE ROWS

,match_id,match_result,home_club,away_club,fixture_date,competition,competition_code,cup_game,home_manager_id,away_manager_id,...,away_club_recent_competition_code_1,away_club_recent_competition_code_2,away_club_recent_competition_code_3,away_club_recent_competition_code_4,away_club_recent_competition_code_5,away_club_recent_competition_code_6,away_club_recent_competition_code_7,away_club_recent_competition_code_8,away_club_recent_competition_code_9,away_club_recent_competition_code_10
110933,18030016,draw,Zamora Fútbol Club,Hermanos Colmenares,2021-04-30 23:00:00,Primera Division,800,False,7708122.0,37564088.0,...,800.0,800.0,1101.0,1101.0,803.0,803.0,803.0,803.0,803.0,803.0
110934,18030096,away,Royal Pari,Oriente Petrolero,2021-04-30 23:00:00,Liga De Futbol Prof,1098,False,465833.0,16488543.0,...,1098.0,1098.0,1098.0,1098.0,1098.0,1098.0,1098.0,1098.0,1098.0,1098.0
110935,17715497,draw,São Bernardo,Água Santa,2021-04-30 23:00:00,Paulista A2,1314,False,8416491.0,528562.0,...,1314.0,1314.0,1314.0,1314.0,1314.0,1314.0,1314.0,1314.0,1746.0,1746.0
110936,17944153,away,Everton,La Serena,2021-05-01 00:00:00,Primera Division,663,False,6973085.0,471757.0,...,663.0,663.0,663.0,663.0,663.0,663.0,663.0,663.0,663.0,663.0
110937,17786297,home,Colón,Arsenal de Sarandi,2021-05-01 00:00:00,Superliga,636,False,213970.0,470859.0,...,1116.0,636.0,1116.0,636.0,636.0,636.0,636.0,636.0,636.0,636.0

======================================================================
DUPLICATED ROWS
0

======================================================================
DATA TYPES

match_id                                  int64
match_result                             object
home_club                                object
away_club                                object
fixture_date                             object
                                         ...
away_club_recent_competition_code_6     float64
away_club_recent_competition_code_7     float64
away_club_recent_competition_code_8     float64
away_club_recent_competition_code_9     float64
away_club_recent_competition_code_10    float64
Length: 190, dtype: object

======================================================================
UNIQUE VALUES PER COLUMN

match_id                                110938
match_result                                 3
home_club                                 9813
away_club                                 9892
fixture_date                             20269
                                         ...
away_club_recent_competition_code_6        828
away_club_recent_competition_code_7        821
away_club_recent_competition_code_8        808
away_club_recent_competition_code_9        791
away_club_recent_competition_code_10       777
Length: 190, dtype: int64

# Data Cleaning

The objective of this step is to improve the quality of the dataset before training machine learning models.

The following preprocessing tasks will be performed:

- Remove unnecessary columns.
- Handle inconsistent columns.
- Remove duplicate records.
- Handle missing values.

The cleaning steps are ordered to maximize data quality. Categorical values are standardized before removing duplicates so that records differing only in formatting are identified as duplicates. Missing values are then handled, followed by data type conversion and categorical encoding to prepare the dataset for machine learning.

These operations ensure that the dataset is clean, consistent, and suitable for machine learning algorithms.

## Remove Unnecessary Columns

The `match_id` column is only an identifier and does not contain predictive information.
Therefore, it is removed from the dataset.

In [16]:
df.drop(columns=["match_id"], inplace=True)

## Consistency Check of Categorical Variables

The categorical variables `home_club`, `away_club`, and `competition` were inspected to identify inconsistent naming, duplicated categories, unnecessary whitespace, and typographical errors.

In [17]:
categorical_cols = ["home_club", "away_club", "competition"]

# Count unique values BEFORE cleaning
before = {}

for col in categorical_cols:
    before[col] = df[col].nunique()

# Cleaning

# Remove unnecessary whitespace
for col in categorical_cols:
    df[col] = (
        df[col]
        .str.strip()
        .replace(r"\s+", " ", regex=True)
    )

# Correct obvious spelling mistakes
competition_mapping = {
    "Permier League Play-offs": "Premier League Play-offs"
}

df["competition"] = df["competition"].replace(competition_mapping)

# Count unique values AFTER cleaning

after = {}

for col in categorical_cols:
    after[col] = df[col].nunique()

# Compare

print("=" * 60)
print("CATEGORICAL CONSISTENCY CHECK")
print("=" * 60)

for col in categorical_cols:
    print(f"{col}")
    print(f"Before cleaning : {before[col]}")
    print(f"After cleaning  : {after[col]}")
    print(f"Corrected       : {before[col] - after[col]}")
    print("-" * 60)

============================================================
CATEGORICAL CONSISTENCY CHECK
============================================================
home_club
Before cleaning : 9813
After cleaning  : 9813
Corrected       : 0
------------------------------------------------------------
away_club
Before cleaning : 9892
After cleaning  : 9892
Corrected       : 0
------------------------------------------------------------
competition
Before cleaning : 727
After cleaning  : 727
Corrected       : 0
------------------------------------------------------------

## Remove Duplicate Records

Duplicate records may negatively affect model performance.
This step removes duplicated rows while keeping the first occurrence.

In [18]:
initial_rows = len(df)

df.drop_duplicates(inplace=True)

print(f"Removed {initial_rows - len(df)} duplicate trip records.")

Removed 17 duplicate trip records.

## Handling Missing Values

Missing values were imputed according to the meaning of each feature instead of applying a single strategy to all columns.

The following rules were used:

- **Manager IDs** were filled with `-1`, indicating that the manager information was unavailable.
- **Cup game** and **played at home** columns were filled with `0`, assuming the match was not a cup game or was not played at home when historical information was missing.
- **Goals scored** and **goals conceded** were filled with `0`, representing no recorded goals in the missing historical match.
- **Team ratings**, **opponent ratings**, and **days since previous match** were filled with the median value of each column to preserve the overall distribution.
- **Categorical features** were filled with `"Unknown"` to retain all observations while explicitly marking missing categories.

This feature-specific strategy preserves the semantic meaning of the data and avoids introducing unnecessary bias.

In [19]:
print("=" * 60)
print("MISSING VALUES BEFORE IMPUTATION")
print(df.isnull().sum().sum())

# -----------------------------
# Column groups
# -----------------------------

# Manager IDs
manager_cols = [c for c in df.columns if "manager_id" in c]

# Binary columns
binary_cols = [c for c in df.columns
               if ("cup_game" in c) or ("played_at_home" in c)]

# Goal columns
goal_cols = [c for c in df.columns
             if ("goals_scored" in c) or ("goals_conceded" in c)]

# Rating columns
rating_cols = [c for c in df.columns
               if ("team_rating" in c) or ("opponent_rating" in c)]

# Rest-day columns
rest_cols = [c for c in df.columns
             if "days_since_match" in c]

# Text columns
categorical_cols = df.select_dtypes(include="object").columns

# -----------------------------
# Imputation
# -----------------------------

# Manager IDs
df[manager_cols] = df[manager_cols].fillna(-1)

# Binary features
df[binary_cols] = df[binary_cols].fillna(0)

# Convert binary columns to integer
for col in binary_cols:
    if df[col].dtype == object:
        df[col] = (
            df[col]
            .replace({True: 1, False: 0, "True": 1, "False": 0})
            .fillna(0)
            .astype(int)
        )
    else:
        df[col] = df[col].astype(int)

# Goals
df[goal_cols] = df[goal_cols].fillna(0)

# Ratings
for col in rating_cols:
    df[col] = df[col].fillna(df[col].median())

# Days since previous match
for col in rest_cols:
    df[col] = df[col].fillna(df[col].median())

# Text columns
for col in categorical_cols:
    df[col] = df[col].fillna("Unknown")

print("\n" + "=" * 60)
print("MISSING VALUES AFTER IMPUTATION")
print(df.isnull().sum().sum())

============================================================
MISSING VALUES BEFORE IMPUTATION
1717146

C:\Users\sarag\AppData\Local\Temp\ipykernel_5724\619668400.py:46: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace({True: 1, False: 0, "True": 1, "False": 0})

============================================================
MISSING VALUES AFTER IMPUTATION
149501

In [20]:
comp_cols = [col for col in df.columns if "recent_competition_code" in col]

competition_cols = [
    col for col in df.columns
    if "recent_competition_code" in col
]

df[competition_cols] = df[competition_cols].fillna(-1)


print("\n" + "=" * 60)
print("MISSING VALUES AFTER IMPUTATION")
print(df.isnull().sum().sum())

============================================================
MISSING VALUES AFTER IMPUTATION
0

In [21]:
df.to_csv("../data/clean_data.csv", index=False)